import { Folder } from "./usePortfolioContext";
import file_0_agenda_demo from "assets/portfolio2/Branding/Agenda/Agenda demo.pdf";
import file_1_biblia_aracne from "assets/portfolio2/Branding/Aracne Phobia/Biblia Aracne.pdf";
import file_2_isologo from "assets/portfolio2/Branding/Aracne Phobia/Isologo.png";
import file_3_logo from "assets/portfolio2/Branding/Aracne Phobia/Logo.png";
import file_4_logo from "assets/portfolio2/Branding/Clínica Estética/Logo.mp4";
import file_5_logo_thumbnail from "assets/portfolio2/Branding/Clínica Estética/Logo.thumbnail.jpg";
import file_6_tecuida from "assets/portfolio2/Branding/Clínica Estética/Tecuida.pdf";
import file_7_biblia_de_estilo from "assets/portfolio2/Branding/Delugram/Biblia de estilo.pdf";
import file_8_delugram_2 from "assets/portfolio2/Branding/Delugram/Delugram 2.mp4";
import file_9_delugram_2_thumbnail from "assets/portfolio2/Branding/Delugram/Delugram 2.thumbnail.jpg";
import file_10_delugram_logo from "assets/portfolio2/Branding/Delugram/delugram logo.gif";
import file_11_delugram_logo from "assets/portfolio2/Branding/Delugram/Delugram Logo.mp4";
import file_12_delugram_logo_thumbnail from "assets/portfolio2/Branding/Delugram/Delugram Logo.thumbnail.jpg";
import file_13_delugram from "assets/portfolio2/Branding/Delugram/Delugram.mp4";
import file_14_delugram_thumbnail from "assets/portfolio2/Branding/Delugram/Delugram.thumbnail.jpg";
import file_15_abrazo from "assets/portfolio2/Branding/Delugram - Graphics/Abrazo.png";
import file_16_amor from "assets/portfolio2/Branding/Delugram - Graphics/Amor.png";
import file_17_corazon from "assets/portfolio2/Branding/Delugram - Graphics/corazon.png";
import file_18_discusion from "assets/portfolio2/Branding/Delugram - Graphics/Discusion.png";
import file_19_img_4434 from "assets/portfolio2/Branding/Delugram - Graphics/IMG_4434.png";
import file_20_llanto from "assets/portfolio2/Branding/Delugram - Graphics/Llanto.png";
import file_21_notificaci_n from "assets/portfolio2/Branding/Delugram - Graphics/Notificación.png";
import file_22_telefono from "assets/portfolio2/Branding/Delugram - Graphics/telefono.png";
import file_23_logo from "assets/portfolio2/Branding/Farmacia/Logo.mp4";
import file_24_logo_thumbnail from "assets/portfolio2/Branding/Farmacia/Logo.thumbnail.jpg";
import file_25_sancho_de_mesa from "assets/portfolio2/Branding/Farmacia/Sancho de Mesa.pdf";
import file_26_biblia_final from "assets/portfolio2/Branding/Jlazz/Biblia final.pdf";
import file_27_logo from "assets/portfolio2/Branding/Jlazz/Logo.mp4";
import file_28_logo_thumbnail from "assets/portfolio2/Branding/Jlazz/Logo.thumbnail.jpg";
import file_29_logo from "assets/portfolio2/Branding/Jlazz/LOGO.png";
import file_30_portrait from "assets/portfolio2/Branding/Jlazz/Portrait.png";
import file_31_doppie_ganger from "assets/portfolio2/Branding/Otros proyectos/Doppie Ganger.jpg";
import file_32_fun_and_food from "assets/portfolio2/Branding/Otros proyectos/Fun and food.png";
import file_33_owned_packaging from "assets/portfolio2/Branding/Otros proyectos/Owned Packaging.png";
import file_34_1 from "assets/portfolio2/Drawing/Concept Art/Aracnephobia/1.png";
import file_35_10 from "assets/portfolio2/Drawing/Concept Art/Aracnephobia/10.png";
import file_36_11 from "assets/portfolio2/Drawing/Concept Art/Aracnephobia/11.png";
import file_37_12 from "assets/portfolio2/Drawing/Concept Art/Aracnephobia/12.png";
import file_38_13 from "assets/portfolio2/Drawing/Concept Art/Aracnephobia/13.png";
import file_39_14 from "assets/portfolio2/Drawing/Concept Art/Aracnephobia/14.png";
import file_40_15 from "assets/portfolio2/Drawing/Concept Art/Aracnephobia/15.png";
import file_41_16 from "assets/portfolio2/Drawing/Concept Art/Aracnephobia/16.png";
import file_42_17 from "assets/portfolio2/Drawing/Concept Art/Aracnephobia/17.png";
import file_43_18 from "assets/portfolio2/Drawing/Concept Art/Aracnephobia/18.png";
import file_44_19 from "assets/portfolio2/Drawing/Concept Art/Aracnephobia/19.png";
import file_45_2 from "assets/portfolio2/Drawing/Concept Art/Aracnephobia/2.png";
import file_46_20 from "assets/portfolio2/Drawing/Concept Art/Aracnephobia/20.png";
import file_47_3 from "assets/portfolio2/Drawing/Concept Art/Aracnephobia/3.png";
import file_48_4 from "assets/portfolio2/Drawing/Concept Art/Aracnephobia/4.png";
import file_49_5 from "assets/portfolio2/Drawing/Concept Art/Aracnephobia/5.png";
import file_50_6 from "assets/portfolio2/Drawing/Concept Art/Aracnephobia/6.png";
import file_51_7 from "assets/portfolio2/Drawing/Concept Art/Aracnephobia/7.png";
import file_52_8 from "assets/portfolio2/Drawing/Concept Art/Aracnephobia/8.png";
import file_53_9 from "assets/portfolio2/Drawing/Concept Art/Aracnephobia/9.png";
import file_54_characters from "assets/portfolio2/Drawing/Concept Art/Book of Mistery/Characters.jpg";
import file_55_dana_colours from "assets/portfolio2/Drawing/Concept Art/Book of Mistery/DANA Colours.jpg";
import file_56_dana_study_2 from "assets/portfolio2/Drawing/Concept Art/Book of Mistery/Dana Study 2.jpg";
import file_57_dana_study from "assets/portfolio2/Drawing/Concept Art/Book of Mistery/Dana Study.jpg";
import file_58_lloyd_study from "assets/portfolio2/Drawing/Concept Art/Book of Mistery/Lloyd Study.jpg";
import file_59_virginia_colours from "assets/portfolio2/Drawing/Concept Art/Book of Mistery/Virginia Colours.jpg";
import file_60_virginia_study_2 from "assets/portfolio2/Drawing/Concept Art/Book of Mistery/Virginia Study 2.jpg";
import file_61_virginia_study from "assets/portfolio2/Drawing/Concept Art/Book of Mistery/Virginia Study.jpg";
import file_62_cell from "assets/portfolio2/Drawing/Concept Art/Delugram/Cell.png";
import file_63_ail_n_pareja from "assets/portfolio2/Drawing/Concept Art/Delugram/Equipo/Ailén pareja.png";
import file_64_ali_amiga from "assets/portfolio2/Drawing/Concept Art/Delugram/Equipo/Ali Amiga.png";
import file_65_ana_padre from "assets/portfolio2/Drawing/Concept Art/Delugram/Equipo/Ana padre.png";
import file_66_avatar_ailen_1 from "assets/portfolio2/Drawing/Concept Art/Delugram/Equipo/Avatar Ailen 1.png";
import file_67_avatar_ail_n_2 from "assets/portfolio2/Drawing/Concept Art/Delugram/Equipo/Avatar Ailén 2.png";
import file_68_avatar_ali_1 from "assets/portfolio2/Drawing/Concept Art/Delugram/Equipo/Avatar Ali 1.png";
import file_69_avatar_ali_2 from "assets/portfolio2/Drawing/Concept Art/Delugram/Equipo/Avatar Ali 2.png";
import file_70_avatar_ana_1 from "assets/portfolio2/Drawing/Concept Art/Delugram/Equipo/Avatar Ana 1.png";
import file_71_avatar_ana_2 from "assets/portfolio2/Drawing/Concept Art/Delugram/Equipo/Avatar Ana 2.png";
import file_72_avatar_colo_3 from "assets/portfolio2/Drawing/Concept Art/Delugram/Equipo/Avatar Colo 3.png";
import file_73_avatar_mar_a_1 from "assets/portfolio2/Drawing/Concept Art/Delugram/Equipo/Avatar María 1.png";
import file_74_card_sorting from "assets/portfolio2/Drawing/Concept Art/Delugram/Equipo/Card Sorting.png";
import file_75_colo_madre_ from "assets/portfolio2/Drawing/Concept Art/Delugram/Equipo/Colo Madre .png";
import file_76_dise_o_de_interfaces from "assets/portfolio2/Drawing/Concept Art/Delugram/Equipo/Diseño de interfaces.png";
import file_77_equipo_2 from "assets/portfolio2/Drawing/Concept Art/Delugram/Equipo/Equipo 2.png";
import file_78_equipo_instant from "assets/portfolio2/Drawing/Concept Art/Delugram/Equipo/Equipo instant.png";
import file_79_equipo_wireframes from "assets/portfolio2/Drawing/Concept Art/Delugram/Equipo/Equipo Wireframes.png";
import file_80_teamwork_1 from "assets/portfolio2/Drawing/Concept Art/Delugram/Equipo/Teamwork 1.png";
import file_81_teamwork_2 from "assets/portfolio2/Drawing/Concept Art/Delugram/Equipo/teamwork 2.png";
import file_82_teamwork_3 from "assets/portfolio2/Drawing/Concept Art/Delugram/Equipo/teamwork 3.png";
import file_83_teamwork_4 from "assets/portfolio2/Drawing/Concept Art/Delugram/Equipo/Teamwork 4.png";
import file_84_abrazo_grupal from "assets/portfolio2/Drawing/Concept Art/Delugram/Fernanda/Abrazo grupal.png";
import file_85_asustada from "assets/portfolio2/Drawing/Concept Art/Delugram/Fernanda/Asustada.png";
import file_86_atenci_n from "assets/portfolio2/Drawing/Concept Art/Delugram/Fernanda/Atención.png";
import file_87_dubitaci_n from "assets/portfolio2/Drawing/Concept Art/Delugram/Fernanda/Dubitación.png";
import file_88_maria_fernanda from "assets/portfolio2/Drawing/Concept Art/Delugram/Fernanda/maria fernanda.png";
import file_89_max_y_fernanda from "assets/portfolio2/Drawing/Concept Art/Delugram/Fernanda/Max y Fernanda.png";
import file_90_preocupaci_n from "assets/portfolio2/Drawing/Concept Art/Delugram/Fernanda/Preocupación.png";
import file_91_sonrisa from "assets/portfolio2/Drawing/Concept Art/Delugram/Fernanda/Sonrisa.png";
import file_92_sorpresa from "assets/portfolio2/Drawing/Concept Art/Delugram/Fernanda/Sorpresa.png";
import file_93_triste from "assets/portfolio2/Drawing/Concept Art/Delugram/Fernanda/Triste.png";
import file_94_fantasmas from "assets/portfolio2/Drawing/Concept Art/Delugram/Max/Fantasmas.png";
import file_95_feliz from "assets/portfolio2/Drawing/Concept Art/Delugram/Max/Feliz.png";
import file_96_llanto_1 from "assets/portfolio2/Drawing/Concept Art/Delugram/Max/LLanto 1.png";
import file_97_llanto_2 from "assets/portfolio2/Drawing/Concept Art/Delugram/Max/Llanto 2.png";
import file_98_max_1 from "assets/portfolio2/Drawing/Concept Art/Delugram/Max/max 1.png";
import file_99_max_doomscrolling from "assets/portfolio2/Drawing/Concept Art/Delugram/Max/Max doomscrolling.png";
import file_100_max_irritada from "assets/portfolio2/Drawing/Concept Art/Delugram/Max/max irritada.png";
import file_101_max_movil from "assets/portfolio2/Drawing/Concept Art/Delugram/Max/Max movil.png";
import file_102_max_photo from "assets/portfolio2/Drawing/Concept Art/Delugram/Max/Max photo.png";
import file_103_max_prot_1_b from "assets/portfolio2/Drawing/Concept Art/Delugram/Max/Max prot 1 b.png";
import file_104_max_prot_1 from "assets/portfolio2/Drawing/Concept Art/Delugram/Max/Max prot 1.png";
import file_105_max_prot_2 from "assets/portfolio2/Drawing/Concept Art/Delugram/Max/Max prot 2.png";
import file_106_max_prot_3 from "assets/portfolio2/Drawing/Concept Art/Delugram/Max/Max prot 3.png";
import file_107_max_tel_fono_llamada from "assets/portfolio2/Drawing/Concept Art/Delugram/Max/Max teléfono llamada.png";
import file_108_max_trist_mov from "assets/portfolio2/Drawing/Concept Art/Delugram/Max/max trist mov.png";
import file_109_max_triste from "assets/portfolio2/Drawing/Concept Art/Delugram/Max/max triste.png";
import file_110_max_tristilla from "assets/portfolio2/Drawing/Concept Art/Delugram/Max/Max tristilla.png";
import file_111_max_y_fernanda from "assets/portfolio2/Drawing/Concept Art/Delugram/Max/Max y fernanda.png";
import file_112_psicologa from "assets/portfolio2/Drawing/Concept Art/Delugram/Max/Psicologa.png";
import file_113_sorpresa from "assets/portfolio2/Drawing/Concept Art/Delugram/Max/Sorpresa.png";
import file_114_sufrimiento from "assets/portfolio2/Drawing/Concept Art/Delugram/Max/Sufrimiento.png";
import file_115_max_y_fernanda from "assets/portfolio2/Drawing/Concept Art/Delugram/Max y Fernanda.png";
import file_116_max_y_travis_2 from "assets/portfolio2/Drawing/Concept Art/Delugram/Max y Travis 2.png";
import file_117_max_y_travis_3 from "assets/portfolio2/Drawing/Concept Art/Delugram/Max y Travis 3.png";
import file_118_max_y_travis_app from "assets/portfolio2/Drawing/Concept Art/Delugram/Max y Travis app.png";
import file_119_max_y_travis_journey from "assets/portfolio2/Drawing/Concept Art/Delugram/Max y Travis Journey.png";
import file_120_max_y_travis from "assets/portfolio2/Drawing/Concept Art/Delugram/Max y Travis.png";
import file_121_todos_felices from "assets/portfolio2/Drawing/Concept Art/Delugram/Todos felices.png";
import file_122_asustado from "assets/portfolio2/Drawing/Concept Art/Delugram/Travis/Asustado.png";
import file_123_buscando from "assets/portfolio2/Drawing/Concept Art/Delugram/Travis/Buscando.png";
import file_124_feliz from "assets/portfolio2/Drawing/Concept Art/Delugram/Travis/Feliz.png";
import file_125_frustrado from "assets/portfolio2/Drawing/Concept Art/Delugram/Travis/Frustrado.png";
import file_126_img_3559 from "assets/portfolio2/Drawing/Concept Art/Delugram/Travis/IMG_3559.png";
import file_127_img_4066 from "assets/portfolio2/Drawing/Concept Art/Delugram/Travis/IMG_4066.png";
import file_128_img_4129 from "assets/portfolio2/Drawing/Concept Art/Delugram/Travis/IMG_4129.png";
import file_129_img_4134 from "assets/portfolio2/Drawing/Concept Art/Delugram/Travis/IMG_4134.png";
import file_130_max_tel_fono from "assets/portfolio2/Drawing/Concept Art/Delugram/Travis/max teléfono.png";
import file_131_preocupado from "assets/portfolio2/Drawing/Concept Art/Delugram/Travis/Preocupado.png";
import file_132_travis_buscando from "assets/portfolio2/Drawing/Concept Art/Delugram/Travis/Travis buscando.png";
import file_133_travis_cell from "assets/portfolio2/Drawing/Concept Art/Delugram/Travis/travis cell.png";
import file_134_travis_feliz from "assets/portfolio2/Drawing/Concept Art/Delugram/Travis/Travis feliz.png";
import file_135_travis_frustrado from "assets/portfolio2/Drawing/Concept Art/Delugram/Travis/travis frustrado.png";
import file_136_travis_preocupado from "assets/portfolio2/Drawing/Concept Art/Delugram/Travis/Travis preocupado.png";
import file_137_travis_prot_1 from "assets/portfolio2/Drawing/Concept Art/Delugram/Travis/Travis prot 1.png";
import file_138_triste from "assets/portfolio2/Drawing/Concept Art/Delugram/Travis/triste.png";
import file_139_abby from "assets/portfolio2/Drawing/Concept Art/El Baúl de las muñecas/Abby.png";
import file_140_cyndra from "assets/portfolio2/Drawing/Concept Art/El Baúl de las muñecas/Cyndra.png";
import file_141_lybas from "assets/portfolio2/Drawing/Concept Art/El Baúl de las muñecas/Lybas.png";
import file_142_midna from "assets/portfolio2/Drawing/Concept Art/El Baúl de las muñecas/Midna.png";
import file_143_avatar_2 from "assets/portfolio2/Drawing/Digital Art/Avatar 2.jpg";
import file_144_avatar from "assets/portfolio2/Drawing/Digital Art/Avatar.jpg";
import file_145_cartoon_avatar from "assets/portfolio2/Drawing/Digital Art/Cartoon Avatar.jpg";
import file_146_comic_prot from "assets/portfolio2/Drawing/Digital Art/Comic prot.jpeg";
import file_147_concept_sticker from "assets/portfolio2/Drawing/Digital Art/Concept Sticker.png";
import file_148_deadly_portrait_1 from "assets/portfolio2/Drawing/Digital Art/Deadly Portrait 1.png";
import file_149_deadly_portrait_2 from "assets/portfolio2/Drawing/Digital Art/Deadly Portrait 2.png";
import file_150_deadly_portrait_3 from "assets/portfolio2/Drawing/Digital Art/Deadly Portrait 3.png";
import file_151_frankenstein from "assets/portfolio2/Drawing/Digital Art/Frankenstein.png";
import file_152_la_princesa_del_pa_s_de_las_maravillas from "assets/portfolio2/Drawing/Digital Art/La princesa del país de las maravillas.jpg";
import file_153_magic from "assets/portfolio2/Drawing/Digital Art/Magic.png";
import file_154_meanwhile from "assets/portfolio2/Drawing/Digital Art/Meanwhile.png";
import file_155_morgue from "assets/portfolio2/Drawing/Digital Art/Morgue.jpg";
import file_156_psycho from "assets/portfolio2/Drawing/Digital Art/Psycho.jpg";
import file_157_sal_n_de_t_ from "assets/portfolio2/Drawing/Digital Art/Salón de té.jpg";
import file_158_teamwork from "assets/portfolio2/Drawing/Digital Art/Teamwork.png";
import file_159_transici_n from "assets/portfolio2/Drawing/Digital Art/Transición.png";
import file_160_0__el_loco from "assets/portfolio2/Drawing/Editorial/0. El loco.png";
import file_161_blas_n_clementina from "assets/portfolio2/Drawing/Editorial/Blasón Clementina.png";
import file_162_blas_n_hamlet from "assets/portfolio2/Drawing/Editorial/Blasón Hamlet.png";
import file_163_blas_n_jekyll from "assets/portfolio2/Drawing/Editorial/Blasón Jekyll.png";
import file_164_blas_n_joker from "assets/portfolio2/Drawing/Editorial/Blasón Joker.png";
import file_165_blas_n_macbeth from "assets/portfolio2/Drawing/Editorial/Blasón Macbeth.png";
import file_166_blas_n_tali from "assets/portfolio2/Drawing/Editorial/Blasón Tali.png";
import file_167_clementina from "assets/portfolio2/Drawing/Editorial/Clementina.png";
import file_168_el_carro from "assets/portfolio2/Drawing/Editorial/El Carro.png";
import file_169_hamlet from "assets/portfolio2/Drawing/Editorial/Hamlet.png";
import file_170_jekyll from "assets/portfolio2/Drawing/Editorial/Jekyll.png";
import file_171_joker from "assets/portfolio2/Drawing/Editorial/Joker.png";
import file_172_macbeth from "assets/portfolio2/Drawing/Editorial/Macbeth.png";
import file_173_sello_clementina from "assets/portfolio2/Drawing/Editorial/Sello Clementina.png";
import file_174_sello_hamlet from "assets/portfolio2/Drawing/Editorial/Sello Hamlet.png";
import file_175_sello_jekyll from "assets/portfolio2/Drawing/Editorial/Sello Jekyll.png";
import file_176_sello_joker from "assets/portfolio2/Drawing/Editorial/Sello Joker.png";
import file_177_sello_macbeth from "assets/portfolio2/Drawing/Editorial/Sello Macbeth.png";
import file_178_sello_tali from "assets/portfolio2/Drawing/Editorial/Sello Tali.png";
import file_179_tali from "assets/portfolio2/Drawing/Editorial/Tali.png";
import file_180_xvi__the_crooked_girl from "assets/portfolio2/Drawing/Editorial/XVI. The crooked girl.png";
import file_181_xx_la_torre from "assets/portfolio2/Drawing/Editorial/XX La torre.png";
import file_182_xxi_la_luna from "assets/portfolio2/Drawing/Editorial/XXI La luna.png";
import file_183_xxi_the_star from "assets/portfolio2/Drawing/Editorial/XXI The star.png";
import file_184_cats_imperium from "assets/portfolio2/Drawing/Tattoo/Cats imperium.png";
import file_185_polter_and_sinestea from "assets/portfolio2/Drawing/Tattoo/Polter and sinestea.png";
import file_186_shinji from "assets/portfolio2/Drawing/Tattoo/Shinji.png";
import file_187_you_are_not_alone from "assets/portfolio2/Drawing/Tattoo/You are not alone.png";
import file_188_delugram from "assets/portfolio2/Reel/Delugram.mp4";
import file_189_delugram_thumbnail from "assets/portfolio2/Reel/Delugram.thumbnail.jpg";
import file_190_jlazz from "assets/portfolio2/Reel/Jlazz.mp4";
import file_191_jlazz_thumbnail from "assets/portfolio2/Reel/Jlazz.thumbnail.jpg";
import file_192_la_morgue_de_aracne from "assets/portfolio2/Reel/La Morgue de Aracne.mp4";
import file_193_la_morgue_de_aracne_thumbnail from "assets/portfolio2/Reel/La Morgue de Aracne.thumbnail.jpg";
import file_194_sdm from "assets/portfolio2/Reel/SdM.mp4";
import file_195_sdm_thumbnail from "assets/portfolio2/Reel/SdM.thumbnail.jpg";
import file_196_tecuida from "assets/portfolio2/Reel/TeCuida.mp4";
import file_197_tecuida_thumbnail from "assets/portfolio2/Reel/TeCuida.thumbnail.jpg";

export function getBrandingFolder () : Folder { const folder: Folder = {type: 'folder',name: "Branding",display: 'list',content: [{type: 'folder',name: "Agenda",display: 'gallery',content: [{type: 'pdf',name: "Agenda demo",content: file_0_agenda_demo,}, ]}, {type: 'folder',name: "Aracne Phobia",display: 'gallery',content: [{type: 'pdf',name: "Biblia Aracne",content: file_1_biblia_aracne,}, {type: 'image',name: "Isologo",content: file_2_isologo,}, {type: 'image',name: "Logo",content: file_3_logo,}, ]}, {type: 'folder',name: "Clínica Estética",display: 'gallery',content: [{type: 'video',name: "Logo",content: file_4_logo,thumbnail: file_5_logo_thumbnail,}, {type: 'pdf',name: "Tecuida",content: file_6_tecuida,}, ]}, {type: 'folder',name: "Delugram",display: 'gallery',content: [{type: 'pdf',name: "Biblia de estilo",content: file_7_biblia_de_estilo,}, {type: 'video',name: "Delugram 2",content: file_8_delugram_2,thumbnail: file_9_delugram_2_thumbnail,}, {type: 'image',name: "delugram logo",content: file_10_delugram_logo,}, {type: 'video',name: "Delugram Logo",content: file_11_delugram_logo,thumbnail: file_12_delugram_logo_thumbnail,}, {type: 'video',name: "Delugram",content: file_13_delugram,thumbnail: file_14_delugram_thumbnail,}, ]}, {type: 'folder',name: "Delugram - Graphics",display: 'gallery',content: [{type: 'image',name: "Abrazo",content: file_15_abrazo,}, {type: 'image',name: "Amor",content: file_16_amor,}, {type: 'image',name: "corazon",content: file_17_corazon,}, {type: 'image',name: "Discusion",content: file_18_discusion,}, {type: 'image',name: "IMG_4434",content: file_19_img_4434,}, {type: 'image',name: "Llanto",content: file_20_llanto,}, {type: 'image',name: "Notificación",content: file_21_notificaci_n,}, {type: 'image',name: "telefono",content: file_22_telefono,}, ]}, {type: 'folder',name: "Farmacia",display: 'gallery',content: [{type: 'video',name: "Logo",content: file_23_logo,thumbnail: file_24_logo_thumbnail,}, {type: 'pdf',name: "Sancho de Mesa",content: file_25_sancho_de_mesa,}, ]}, {type: 'folder',name: "Jlazz",display: 'gallery',content: [{type: 'pdf',name: "Biblia final",content: file_26_biblia_final,}, {type: 'video',name: "Logo",content: file_27_logo,thumbnail: file_28_logo_thumbnail,}, {type: 'image',name: "LOGO",content: file_29_logo,}, {type: 'image',name: "Portrait",content: file_30_portrait,}, ]}, {type: 'folder',name: "Otros proyectos",display: 'gallery',content: [{type: 'image',name: "Doppie Ganger",content: file_31_doppie_ganger,}, {type: 'image',name: "Fun and food",content: file_32_fun_and_food,}, {type: 'image',name: "Owned Packaging",content: file_33_owned_packaging,}, ]}, ]};return folder;};export function getDrawingFolder () : Folder { const folder: Folder = {type: 'folder',name: "Drawing",display: 'list',content: [{type: 'folder',name: "Concept Art",display: 'list',content: [{type: 'folder',name: "Aracnephobia",display: 'gallery',content: [{type: 'image',name: "1",content: file_34_1,}, {type: 'image',name: "10",content: file_35_10,}, {type: 'image',name: "11",content: file_36_11,}, {type: 'image',name: "12",content: file_37_12,}, {type: 'image',name: "13",content: file_38_13,}, {type: 'image',name: "14",content: file_39_14,}, {type: 'image',name: "15",content: file_40_15,}, {type: 'image',name: "16",content: file_41_16,}, {type: 'image',name: "17",content: file_42_17,}, {type: 'image',name: "18",content: file_43_18,}, {type: 'image',name: "19",content: file_44_19,}, {type: 'image',name: "2",content: file_45_2,}, {type: 'image',name: "20",content: file_46_20,}, {type: 'image',name: "3",content: file_47_3,}, {type: 'image',name: "4",content: file_48_4,}, {type: 'image',name: "5",content: file_49_5,}, {type: 'image',name: "6",content: file_50_6,}, {type: 'image',name: "7",content: file_51_7,}, {type: 'image',name: "8",content: file_52_8,}, {type: 'image',name: "9",content: file_53_9,}, ]}, {type: 'folder',name: "Book of Mistery",display: 'gallery',content: [{type: 'image',name: "Characters",content: file_54_characters,}, {type: 'image',name: "DANA Colours",content: file_55_dana_colours,}, {type: 'image',name: "Dana Study 2",content: file_56_dana_study_2,}, {type: 'image',name: "Dana Study",content: file_57_dana_study,}, {type: 'image',name: "Lloyd Study",content: file_58_lloyd_study,}, {type: 'image',name: "Virginia Colours",content: file_59_virginia_colours,}, {type: 'image',name: "Virginia Study 2",content: file_60_virginia_study_2,}, {type: 'image',name: "Virginia Study",content: file_61_virginia_study,}, ]}, {type: 'folder',name: "Delugram",display: 'gallery',content: [{type: 'image',name: "Cell",content: file_62_cell,}, {type: 'folder',name: "Equipo",display: 'gallery',content: [{type: 'image',name: "Ailén pareja",content: file_63_ail_n_pareja,}, {type: 'image',name: "Ali Amiga",content: file_64_ali_amiga,}, {type: 'image',name: "Ana padre",content: file_65_ana_padre,}, {type: 'image',name: "Avatar Ailen 1",content: file_66_avatar_ailen_1,}, {type: 'image',name: "Avatar Ailén 2",content: file_67_avatar_ail_n_2,}, {type: 'image',name: "Avatar Ali 1",content: file_68_avatar_ali_1,}, {type: 'image',name: "Avatar Ali 2",content: file_69_avatar_ali_2,}, {type: 'image',name: "Avatar Ana 1",content: file_70_avatar_ana_1,}, {type: 'image',name: "Avatar Ana 2",content: file_71_avatar_ana_2,}, {type: 'image',name: "Avatar Colo 3",content: file_72_avatar_colo_3,}, {type: 'image',name: "Avatar María 1",content: file_73_avatar_mar_a_1,}, {type: 'image',name: "Card Sorting",content: file_74_card_sorting,}, {type: 'image',name: "Colo Madre ",content: file_75_colo_madre_,}, {type: 'image',name: "Diseño de interfaces",content: file_76_dise_o_de_interfaces,}, {type: 'image',name: "Equipo 2",content: file_77_equipo_2,}, {type: 'image',name: "Equipo instant",content: file_78_equipo_instant,}, {type: 'image',name: "Equipo Wireframes",content: file_79_equipo_wireframes,}, {type: 'image',name: "Teamwork 1",content: file_80_teamwork_1,}, {type: 'image',name: "teamwork 2",content: file_81_teamwork_2,}, {type: 'image',name: "teamwork 3",content: file_82_teamwork_3,}, {type: 'image',name: "Teamwork 4",content: file_83_teamwork_4,}, ]}, {type: 'folder',name: "Fernanda",display: 'gallery',content: [{type: 'image',name: "Abrazo grupal",content: file_84_abrazo_grupal,}, {type: 'image',name: "Asustada",content: file_85_asustada,}, {type: 'image',name: "Atención",content: file_86_atenci_n,}, {type: 'image',name: "Dubitación",content: file_87_dubitaci_n,}, {type: 'image',name: "maria fernanda",content: file_88_maria_fernanda,}, {type: 'image',name: "Max y Fernanda",content: file_89_max_y_fernanda,}, {type: 'image',name: "Preocupación",content: file_90_preocupaci_n,}, {type: 'image',name: "Sonrisa",content: file_91_sonrisa,}, {type: 'image',name: "Sorpresa",content: file_92_sorpresa,}, {type: 'image',name: "Triste",content: file_93_triste,}, ]}, {type: 'folder',name: "Max",display: 'gallery',content: [{type: 'image',name: "Fantasmas",content: file_94_fantasmas,}, {type: 'image',name: "Feliz",content: file_95_feliz,}, {type: 'image',name: "LLanto 1",content: file_96_llanto_1,}, {type: 'image',name: "Llanto 2",content: file_97_llanto_2,}, {type: 'image',name: "max 1",content: file_98_max_1,}, {type: 'image',name: "Max doomscrolling",content: file_99_max_doomscrolling,}, {type: 'image',name: "max irritada",content: file_100_max_irritada,}, {type: 'image',name: "Max movil",content: file_101_max_movil,}, {type: 'image',name: "Max photo",content: file_102_max_photo,}, {type: 'image',name: "Max prot 1 b",content: file_103_max_prot_1_b,}, {type: 'image',name: "Max prot 1",content: file_104_max_prot_1,}, {type: 'image',name: "Max prot 2",content: file_105_max_prot_2,}, {type: 'image',name: "Max prot 3",content: file_106_max_prot_3,}, {type: 'image',name: "Max teléfono llamada",content: file_107_max_tel_fono_llamada,}, {type: 'image',name: "max trist mov",content: file_108_max_trist_mov,}, {type: 'image',name: "max triste",content: file_109_max_triste,}, {type: 'image',name: "Max tristilla",content: file_110_max_tristilla,}, {type: 'image',name: "Max y fernanda",content: file_111_max_y_fernanda,}, {type: 'image',name: "Psicologa",content: file_112_psicologa,}, {type: 'image',name: "Sorpresa",content: file_113_sorpresa,}, {type: 'image',name: "Sufrimiento",content: file_114_sufrimiento,}, ]}, {type: 'image',name: "Max y Fernanda",content: file_115_max_y_fernanda,}, {type: 'image',name: "Max y Travis 2",content: file_116_max_y_travis_2,}, {type: 'image',name: "Max y Travis 3",content: file_117_max_y_travis_3,}, {type: 'image',name: "Max y Travis app",content: file_118_max_y_travis_app,}, {type: 'image',name: "Max y Travis Journey",content: file_119_max_y_travis_journey,}, {type: 'image',name: "Max y Travis",content: file_120_max_y_travis,}, {type: 'image',name: "Todos felices",content: file_121_todos_felices,}, {type: 'folder',name: "Travis",display: 'gallery',content: [{type: 'image',name: "Asustado",content: file_122_asustado,}, {type: 'image',name: "Buscando",content: file_123_buscando,}, {type: 'image',name: "Feliz",content: file_124_feliz,}, {type: 'image',name: "Frustrado",content: file_125_frustrado,}, {type: 'image',name: "IMG_3559",content: file_126_img_3559,}, {type: 'image',name: "IMG_4066",content: file_127_img_4066,}, {type: 'image',name: "IMG_4129",content: file_128_img_4129,}, {type: 'image',name: "IMG_4134",content: file_129_img_4134,}, {type: 'image',name: "max teléfono",content: file_130_max_tel_fono,}, {type: 'image',name: "Preocupado",content: file_131_preocupado,}, {type: 'image',name: "Travis buscando",content: file_132_travis_buscando,}, {type: 'image',name: "travis cell",content: file_133_travis_cell,}, {type: 'image',name: "Travis feliz",content: file_134_travis_feliz,}, {type: 'image',name: "travis frustrado",content: file_135_travis_frustrado,}, {type: 'image',name: "Travis preocupado",content: file_136_travis_preocupado,}, {type: 'image',name: "Travis prot 1",content: file_137_travis_prot_1,}, {type: 'image',name: "triste",content: file_138_triste,}, ]}, ]}, {type: 'folder',name: "El Baúl de las muñecas",display: 'gallery',content: [{type: 'image',name: "Abby",content: file_139_abby,}, {type: 'image',name: "Cyndra",content: file_140_cyndra,}, {type: 'image',name: "Lybas",content: file_141_lybas,}, {type: 'image',name: "Midna",content: file_142_midna,}, ]}, ]}, {type: 'folder',name: "Digital Art",display: 'gallery',content: [{type: 'image',name: "Avatar 2",content: file_143_avatar_2,}, {type: 'image',name: "Avatar",content: file_144_avatar,}, {type: 'image',name: "Cartoon Avatar",content: file_145_cartoon_avatar,}, {type: 'image',name: "Comic prot",content: file_146_comic_prot,}, {type: 'image',name: "Concept Sticker",content: file_147_concept_sticker,}, {type: 'image',name: "Deadly Portrait 1",content: file_148_deadly_portrait_1,}, {type: 'image',name: "Deadly Portrait 2",content: file_149_deadly_portrait_2,}, {type: 'image',name: "Deadly Portrait 3",content: file_150_deadly_portrait_3,}, {type: 'image',name: "Frankenstein",content: file_151_frankenstein,}, {type: 'image',name: "La princesa del país de las maravillas",content: file_152_la_princesa_del_pa_s_de_las_maravillas,}, {type: 'image',name: "Magic",content: file_153_magic,}, {type: 'image',name: "Meanwhile",content: file_154_meanwhile,}, {type: 'image',name: "Morgue",content: file_155_morgue,}, {type: 'image',name: "Psycho",content: file_156_psycho,}, {type: 'image',name: "Salón de té",content: file_157_sal_n_de_t_,}, {type: 'image',name: "Teamwork",content: file_158_teamwork,}, {type: 'image',name: "Transición",content: file_159_transici_n,}, ]}, {type: 'folder',name: "Editorial",display: 'gallery',content: [{type: 'image',name: "0. El loco",content: file_160_0__el_loco,}, {type: 'image',name: "Blasón Clementina",content: file_161_blas_n_clementina,}, {type: 'image',name: "Blasón Hamlet",content: file_162_blas_n_hamlet,}, {type: 'image',name: "Blasón Jekyll",content: file_163_blas_n_jekyll,}, {type: 'image',name: "Blasón Joker",content: file_164_blas_n_joker,}, {type: 'image',name: "Blasón Macbeth",content: file_165_blas_n_macbeth,}, {type: 'image',name: "Blasón Tali",content: file_166_blas_n_tali,}, {type: 'image',name: "Clementina",content: file_167_clementina,}, {type: 'image',name: "El Carro",content: file_168_el_carro,}, {type: 'image',name: "Hamlet",content: file_169_hamlet,}, {type: 'image',name: "Jekyll",content: file_170_jekyll,}, {type: 'image',name: "Joker",content: file_171_joker,}, {type: 'image',name: "Macbeth",content: file_172_macbeth,}, {type: 'image',name: "Sello Clementina",content: file_173_sello_clementina,}, {type: 'image',name: "Sello Hamlet",content: file_174_sello_hamlet,}, {type: 'image',name: "Sello Jekyll",content: file_175_sello_jekyll,}, {type: 'image',name: "Sello Joker",content: file_176_sello_joker,}, {type: 'image',name: "Sello Macbeth",content: file_177_sello_macbeth,}, {type: 'image',name: "Sello Tali",content: file_178_sello_tali,}, {type: 'image',name: "Tali",content: file_179_tali,}, {type: 'image',name: "XVI. The crooked girl",content: file_180_xvi__the_crooked_girl,}, {type: 'image',name: "XX La torre",content: file_181_xx_la_torre,}, {type: 'image',name: "XXI La luna",content: file_182_xxi_la_luna,}, {type: 'image',name: "XXI The star",content: file_183_xxi_the_star,}, ]}, {type: 'folder',name: "Tattoo",display: 'gallery',content: [{type: 'image',name: "Cats imperium",content: file_184_cats_imperium,}, {type: 'image',name: "Polter and sinestea",content: file_185_polter_and_sinestea,}, {type: 'image',name: "Shinji",content: file_186_shinji,}, {type: 'image',name: "You are not alone",content: file_187_you_are_not_alone,}, ]}, ]};return folder;};export function getReelsFolder () : Folder { const folder: Folder = {type: 'folder',name: "Reel",display: 'gallery',content: [{type: 'video',name: "Delugram",content: file_188_delugram,thumbnail: file_189_delugram_thumbnail,}, {type: 'video',name: "Jlazz",content: file_190_jlazz,thumbnail: file_191_jlazz_thumbnail,}, {type: 'video',name: "La Morgue de Aracne",content: file_192_la_morgue_de_aracne,thumbnail: file_193_la_morgue_de_aracne_thumbnail,}, {type: 'video',name: "SdM",content: file_194_sdm,thumbnail: file_195_sdm_thumbnail,}, {type: 'video',name: "TeCuida",content: file_196_tecuida,thumbnail: file_197_tecuida_thumbnail,}, ]};return folder;};